import id from "bson-objectid";

export const data = [
  {
    id: id(),
    type: "expenses",
    date: "11.01.2011",
    description: "Beef",
    category: "food",
    sum: "450",
  },

  {
    id: id(),
    date: "21.01.2021",
    type: "expenses",
    description: "Salmon",
    category: "food",
    sum: "300",
  },
  {
    id: id(),
    date: "01.01.2001",
    type: "expenses",
    description: "Macallan",
    category: "drinks",
    sum: "18500",
  },
  {
    id: id(),
    date: "21.01.2021",
    type: "expenses",
    description: "Salmon",
    category: "food",
    sum: "300",
  },
  {
    id: id(),
    date: "01.01.2001",
    type: "income",
    description: "Macallan",
    category: "drinks",
    sum: "18500",
  },
  {
    id: id(),
    date: "21.01.2021",
    type: "income",
    description: "Salmon",
    category: "food",
    sum: "300",
  },
  {
    id: id(),
    date: "01.01.2001",
    type: "income",
    description: "Macallan",
    category: "drinks",
    sum: "18500",
  },
  {
    id: id(),
    date: "21.01.2021",
    type: "income",
    description: "Salmon",
    category: "food",
    sum: "300",
  },
  {
    id: id(),
    date: "01.01.2001",
    type: "income",
    description: "Macallan",
    category: "drinks",
    sum: "18500",
  },
  {
    id: id(),
    date: "11.01.2011",
    type: "income",
    description: "Borjomi",
    category: "drinks",
    sum: "450",
  },
  {
    id: id(),
    date: "21.01.2021",
    type: "expenses",
    description: "Salmon",
    category: "food",
    sum: "300",
  },
  {
    id: id(),
    date: "01.01.2001",
    type: "expenses",
    description: "Macallan",
    category: "drinks",
    sum: "18500",
  },
  {
    id: id(),
    type: "expenses",
    date: "11.01.2011",
    description: "Borjomi",
    category: "drinks",
    sum: "450",
  },
  {
    id: id(),
    type: "expenses",
    date: "21.01.2021",
    description: "Salmon",
    category: "food",
    sum: "300",
  },
];
